#!/usr/bin/env python3
import time, json, sys
import smtplib
from email.message import EmailMessage
import paho.mqtt.client as mqtt
from picamera2 import Picamera2
from upload_cloudinary import upload_image
from gpiozero import Button

SENDER_EMAIL = "stephenkerry2013@gmail.com"
SENDER_PASSWORD = "susw hjmq mqqk ldnx"
RECEIVER_EMAIL = "stephenkerry2013@gmail.com"

MQTT_TOPIC = "/stephenpi/event/doorbell"
LOCAL_IMAGE = "last_visitor.jpg"
keep_running = True

client = mqtt.Client()
client.connect("broker.hivemq.com", 1883, 60)
client.loop_start()

picam2 = Picamera2()
picam2.configure(picam2.create_still_configuration())
picam2.start()

button = Button(6, pull_up=True, bounce_time=0.3)

def send_email_notification(image_url):
    try:
        msg = EmailMessage()
        msg.set_content(f"Doorbell Alert!\n\nSomeone just pressed your doorbell.\n\nView the visitor photo here: {image_url}")
        msg['Subject'] = 'Someone is at the Door!'
        msg['From'] = SENDER_EMAIL
        msg['To'] = RECEIVER_EMAIL

        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(SENDER_EMAIL, SENDER_PASSWORD)
            smtp.send_message(msg)
        print("Email notification sent!")
    except Exception as e:
        print(f"Error: {e}")

def doorbell_process():
    global keep_running
    try:
        # Added message for GPIO 6 trigger
        print("Button Pressed!")
        
        picam2.capture_file(LOCAL_IMAGE)
        url = upload_image(LOCAL_IMAGE)
        if url:
            client.publish(MQTT_TOPIC, json.dumps({"image": url, "ts": int(time.time())}))
            send_email_notification(url)
            keep_running = False
    except Exception as e:
        print(f"Error: {e}")
        keep_running = False

print("Doorbell System Active.")
print("Listening for button press on GPIO 6...")

try:
    while keep_running:
        if button.is_pressed:
            doorbell_process()
        time.sleep(0.1)
finally:
    print("Cleaning up resources...")
    picam2.stop()
    client.loop_stop()
    client.disconnect()
    sys.exit(0)
